package rules

import model.User;

global repo.UserRepository userRepo;
global repo.ModerationEventsRepository modRepo;

agenda-group "user-detect"

// R1: > 5 prijava u 24h -> ban objava 24h
rule "Detect: 5+ reports in 24h -> post ban 24h"
when
    $u : User()
    eval( modRepo.countReportsAgainstUserInHours($u.getId(), 24) > 5 )
then
    userRepo.suspendPostingHours($u.getId(), 24);
    modRepo.addFlag($u.getId(), "5+ prijava u 24h -> zabrana objavljivanja 24h", userRepo.postingSuspendedUntil($u.getId()));
end

// R2: > 8 prijava u 48h -> ban objava 48h
rule "Detect: 8+ reports in 48h -> post ban 48h"
when
    $u : User()
    eval( modRepo.countReportsAgainstUserInHours($u.getId(), 48) > 8 )
then
    userRepo.suspendPostingHours($u.getId(), 48);
    modRepo.addFlag($u.getId(), "8+ prijava u 48h -> zabrana objavljivanja 48h", userRepo.postingSuspendedUntil($u.getId()));
end

// R3: > 4 blokiranja u 24h -> ban objava 24h
rule "Detect: 4+ blocked in 24h -> post ban 24h"
when
    $u : User()
    eval( modRepo.countBlocksAgainstUserInHours($u.getId(), 24) > 4 )
then
    userRepo.suspendPostingHours($u.getId(), 24);
    modRepo.addFlag($u.getId(), "4+ puta blokiran u 24h -> zabrana objavljivanja 24h", userRepo.postingSuspendedUntil($u.getId()));
end

// R4: >2 blokiranja u 48h i >4 prijave u 24h -> login ban 48h
rule "Detect: (2+ blocks /48h) AND (4+ reports /24h) -> login ban 48h"
when
    $u : User()
    eval( modRepo.countBlocksAgainstUserInHours($u.getId(), 48) > 2 )
    eval( modRepo.countReportsAgainstUserInHours($u.getId(), 24) > 4 )
then
    userRepo.suspendLoginHours($u.getId(), 48);
    modRepo.addFlag($u.getId(), "2+ blokiranja/48h i 4+ prijave/24h -> zabrana logovanja 48h", userRepo.loginSuspendedUntil($u.getId()));
end


// R5: 3+ različitih blokiranja u 12h -> post ban 24h
rule "Detect: 3+ blocks in 12h -> post ban 24h"
when
    $u : User()
    eval( modRepo.countBlocksAgainstUserInHours($u.getId(), 12) > 2 )
then
    userRepo.suspendPostingHours($u.getId(), 24);
    modRepo.addFlag($u.getId(), "3+ blokiranja u 12h -> zabrana objavljivanja 24h", userRepo.postingSuspendedUntil($u.getId()));
end

// R6: 10+ prijava u 7 dana -> login ban 72h
rule "Detect: 10+ reports in 7d -> login ban 72h"
when
    $u : User()
    eval( modRepo.countReportsAgainstUserInDays($u.getId(), 7) > 10 )
then
    userRepo.suspendLoginHours($u.getId(), 72);
    modRepo.addFlag($u.getId(), "10+ prijava u 7 dana -> zabrana logovanja 72h", userRepo.loginSuspendedUntil($u.getId()));
end
